In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from regression import get_dataset
from regression import print_stats
from regression import regression
from regression import gradient_descent
from regression import iterate_gradient
from regression import compute_betas
from regression import predict
from regression import synthetic_datasets
from regression import plot_mse

In [2]:
dataset = get_dataset("bodyfat.csv")
dataset

array([[12.6   ,  1.0708, 23.    , ..., 32.    , 27.4   , 17.1   ],
       [ 6.9   ,  1.0853, 22.    , ..., 30.5   , 28.9   , 18.2   ],
       [24.6   ,  1.0414, 22.    , ..., 28.8   , 25.2   , 16.6   ],
       ...,
       [28.3   ,  1.0328, 72.    , ..., 31.3   , 27.2   , 18.    ],
       [25.3   ,  1.0399, 72.    , ..., 30.5   , 29.4   , 19.8   ],
       [30.7   ,  1.0271, 74.    , ..., 33.7   , 30.    , 20.9   ]])

In [3]:
dataset.shape

(252, 16)

In [4]:
print_stats(dataset,1)

252
1.06
0.02


In [5]:
regression(dataset, cols=[2,3], betas=[0,0,0])

418.50384920634923

In [6]:
regression(dataset, cols=[2,3,4], betas=[0,-1.1,-.2,3])

11859.17408611111

In [7]:
gradient_descent(dataset, cols=[2,3], betas=[0,0,0])

array([  -37.87698413, -1756.37222222, -7055.35138889])

In [8]:
gradient_descent(dataset, cols=[2,3,4], betas=[0,-1.1,-.2,3])

array([  212.69928571,  9097.25626984, 37643.40848413, 15009.96069444])

In [9]:
iterate_gradient(dataset, cols=[1,8], betas=[400,-400,300], T=10, eta=1e-4)

1 423085332.40 394.45 -405.84 -220.18
2 229744495.73 398.54 -401.54 163.14
3 124756241.68 395.53 -404.71 -119.33
4 67745350.04 397.75 -402.37 88.82
5 36787203.39 396.11 -404.09 -64.57
6 19976260.50 397.32 -402.82 48.47
7 10847555.07 396.43 -403.76 -34.83
8 5890470.68 397.09 -403.07 26.55
9 3198666.69 396.60 -403.58 -18.68
10 1736958.93 396.96 -403.20 14.65


In [21]:
compute_betas(dataset, cols=[1,2])

(1.4029395600144448,
 441.35259435956186,
 -400.59549536886107,
 0.009892204826171282)

In [23]:
predict(dataset, cols=[3,4], features=[180, 72])

17.93538556100129

In [ ]:
synthetic_datasets(np.array([0,2]), np.array([0,1]), np.array([[4]]), 1)

In [ ]:
plot_mse()